// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqueiZVVH9lYcm4jyxTZ8PfXpAIEL8Cd8',
    appId: '1:338166957849:web:3809c3f611185b91ae2788',
    messagingSenderId: '338166957849',
    projectId: 'projeto-firebase-0',
    authDomain: 'projeto-firebase-0.firebaseapp.com',
    storageBucket: 'projeto-firebase-0.firebasestorage.app',
    measurementId: 'G-NBL4W2KZY2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqueiZVVH9lYcm4jyxTZ8PfXpAIEL8Cd8',
    appId: '1:338166957849:web:3809c3f611185b91ae2788',
    messagingSenderId: '338166957849',
    projectId: 'projeto-firebase-0',
    authDomain: 'projeto-firebase-0.firebaseapp.com',
    storageBucket: 'projeto-firebase-0.firebasestorage.app',
    measurementId: 'G-NBL4W2KZY2',
  );

}